---
repos:
  - repo: https://github.com/jumanjihouse/pre-commit-hooks.git
    rev: 1.11.2
    hooks:
      - id: shellcheck
  - repo: https://github.com/igorshubovych/markdownlint-cli.git
    rev: v0.21.0
    hooks:
      - id: markdownlint
  - repo: 'https://github.com/pre-commit/pre-commit-hooks'
    rev: v2.2.3
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-vcs-permalinks
      - id: check-yaml
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: no-commit-to-branch
      - id: requirements-txt-fixer
      - id: trailing-whitespace
